services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mybackendkomut
    ports:
      - "8080:8080"
    environment:
      # 1) Postgres bağlantı bilgileri
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_SCHEMA: read
      GOOGLE_APPLICATION_CREDENTIALS: /app/alto-word-ai-firebase-adminsdk.json
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:14.17-alpine3.20
    container_name: mydbkomut
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      # 1) Postgres veri klasörü (kalıcı veri)
      - pgdata:/var/lib/postgresql/data
      # 2) init/ altındaki tüm .sql otomatik çalışsın
      - ./db2/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myfrontendkomut
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  pgdata: